### ISSUE TITLE
view has Visual Objects

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#16]
the documentation should state that views return Visual Objects rather than the concepts

**Comment by jbsarrodie** [comment]
This is explained in the [overview](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-Overview). Maybe it isn't clear enough.

**Comment by gedwardroberts** [comment]
no... was not clear to me...... needs to be in the jArchi doc...


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by gedwardroberts** [comment]
so there is definitely a difference between $("view") (collection of views)
and $(view) (collection of the children of the view) where view comes from
$("view").each(function(view){...

still, don't understand when I can do this $(view) to get a collection...
and why view.children() does not work but $(view) does?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
`"view"` is a selector. So $("view") returns a collection of all views in the current model.

`view` means nothing unless it happens to be a variable name as in:

`var view = $("view").first();`

If you have a single instance of a view, there is no `children()` method for it. The `children()` method exists on a collection. So doing `$(view)` wraps the single view object in a collection (of one member) and thus the `children()` method can be invoked on it.

```javascript
var collectionOfViews = $("view"); //collection
var allChildren = collectionOfViews.children(); // collection

var firstView = collectionOfViews.first(); // not a collection but a single object
firstView.children(); // <----- NOT VALID!
$(firstView).children(); // <----- VALID
```

**Comment by gedwardroberts** [comment]
why isn't a view a collection of the Visual Object it contains?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
Because a view consists of more than just its children:

- name
- description
- viewpoint
- properties
- children

`children()` for a view in jArchi returns the view's immediate child view objects and all connections.

**Comment by Phillipus** [comment]
@jbsarrodie 

The follwing methods only apply to a `EObjectProxyCollection`. It seems that users may want to access these methods on a single object (`EObjectProxy`):

```javascript
attr()
children()
find()
parent()
parents()
```

The exceptions to those are these methods:

```javascript
objectRefs()
viewRefs()
inRels()
outRels()
```
These methods are available in a collection and single object.

Should we make these methods consistent one way or the other?
Should we allow access on the single object?
Or do we need to make clearer why some methods are only available on a collection?

**Comment by jbsarrodie** [comment]
>Should we make these methods consistent one way or the other?
>Should we allow access on the single object?

No

>Or do we need to make clearer why some methods are only available on a collection?

Yes.

My personal view on this:
- Making the same methods accessible from several places is not good because at the end the API is not clear and users won't know which one to call and will soon start getting unexpected results.
- Each of those methods have variations with selector (and at some point will also accept  function/predicate like for filter). So maintaining all those variations in lots of places will be error prone (and will take time)
- This is the way jQuery works, and this is for a good reason: jQuery (like jArchi) offers a collectioin oriented API on top of a basic/raw element based API. The goal in jArchi is not to replicate the underlying EMF API, so we have:
  - A powerful collection API (EObjectProxyCollection) that manages all "selection" and "navigation" aspects
  - A simple object API (EObjectProxy and siilar classes) that manages getting/setting attributes

**Comment by Phillipus** [comment]
> A simple object API (EObjectProxy and siilar classes) that manages getting/setting attributes

It could be argued that attr() and children() are these type of "getting" attributes.

I think that users will often want to get the children of a given single object. For example, child folders of a folder, or child components in a view. Wrapping the single object in $() is probably going to cause friction. So if this is how it is we really have to make this much clearer.

**Comment by jbsarrodie** [comment]
>It could be argued that attr() and children() are these type of "getting" attributes.

In my mind an attribute can't be a collection.

>I think that users will often want to get the children of a given single object. For example, child folders of a folder, or child components in a view. 

IMHO this is the pandora box, if we add .children() then people will start wondering why you have to to view.children().find() to get all descendant, then we'll add .find(), then.. etc, etc...

>Wrapping the single object in $() is probably going to cause friction.

Not sure, I trained three colleagues and this didn't raise a question, but that's certainly because I explained it clearly, which leads to...

>So if this is how it is we really have to make this much clearer.

Yes, this has to be better explained in the API Overview, with some additional notes wherever needed in API documentation.

**Comment by Phillipus** [comment]
I'm "playing devil's advocate" here in order to make this clearer. ;-)
