### ISSUE TITLE
Support creating new views and visual components

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#26]
We have not yet implemented adding/creating new views and diagram components.

Views
ArchiMate objects (using an existing element and with a new element)
ArchiMate connections (using an existing relationship and with a new relationship )
Notes
Groups
Other Connections
Canvas and Sketch components

- What is the best API for these?
- Which proxy or util classes should own the add/create methods? (For example, one can add an object to a View and also as a child of another object)

**Comment by jbsarrodie** [comment]
First thoughts:
- DiagramModelProxy should expose method to create visual objects that are then located inside the view but not visualy nested (ie: the view is the parent container):
  - DiagramModelComponentProxy add(ArchimateElementProxy) // Add an element to a view and return the visual object. Should use safe defaults for font, color, position...
  - DiagramModelConnectionProxy add(ArchimateRelationshipProxy, DiagramModelComponentProxy, DiagramModelComponentProxy) // Add a relationship to a view. source and target visual objects are passed as arguments.
  - createNote(...) // create and add a note and return it
  - createGroup(...) // create and add a group and return it
  - createConnection(DiagramModelComponentProxy, DiagramModelComponentProxy) // create and return a connection (not an archimate relationship). source and target visual objects are passed as arguments.
 - DiagramModelObjectProxy should expose an .add(DiagramModelComponentProxy) method that would make the passed object a (visual) children of the visual object. It might be nice to automatically convert coordinates so that the object doesn't move (but there are pros&cons). Warning: the passed object should be a descendant of the view (ie we don't want to reference a visual object that belong to another view)
  - DiagramModelProxy should expose a similar .add(DiagramModelComponentProxy). Same warning applied.

**Comment by Phillipus** [comment]
Added:

```
ArchimateModelProxy#createArchimateView(name)
ArchimateModelProxy#createArchimateView(name, parentFolder)

ArchimateModelProxy#createSketchView(name)
ArchimateModelProxy#createSketchView(name, parentFolder)

ArchimateModelProxy#createCanvasView(name)
ArchimateModelProxy#createCanvasView(name, parentFolder)
```

**Comment by Phillipus** [comment]
Added:

```js
DiagramModelProxy#createObject(type, x, y, width, height); // (abstract class of views)
ArchimateDiagramModelProxy#add(element, x, y, width, height);
ArchimateDiagramModelProxy#add(relation, source, target);

DiagramModelObjectProxy#createObject(type, x, y, width, height); 
DiagramModelObjectProxy#add(element, x, y, width, height);
```

**Comment by smileham** [comment]
Would this also include the ability to retrieve the content of a "Note" object?

**Comment by Phillipus** [comment]
Yes. Select a note and call:

var text = selection.first().text;

**Comment by smileham** [comment]
Excellent, thanks Phillipus...

**Comment by Phillipus** [comment]
> We have not yet implemented adding/creating new views and diagram components.

We have now. Closing
