### ISSUE TITLE
jArchi: add CSS for styling elements on diagrams

### ISSUE THREAD

**Issue by robkamp** [archimatetool/archi-scripting-plugin#63]
It would be nice to be able to access the styling/css of an element using jArchi

**Comment by Phillipus** [comment]
You can access colour and opacity for an element. Is this what you mean?

**Comment by robkamp** [comment]
No, I want to be able to split the element into vertical or horizontal rectangles and colour each rectangle based on the colour of the concepts from the incoming relations. This, to show what concept is linked to other concepts by colour. 

Or maybe per value of a property of a related concept.

**Comment by Phillipus** [comment]
That's not possible. The native Archi code simply fills the element with one colour.

**Comment by robkamp** [comment]
> That's not possible. The native Archi code simply fills the element with one colour.

Hence the feature request :-)

**Comment by jbsarrodie** [comment]
>Hence the feature request :-)

What Phil want to say is that this is simply not possible because not supported by underlying framework.

And BTW, this is not based on web technologies so nothing similar to CSS on this part of the framework (which, I can understand, is somewhat confusing because eclipse theme engine implement something very similar to CSS and jArchi mimics jQuery and uses javascript...)

**Comment by robkamp** [comment]
Oh, right. That's a pity.
