### ISSUE TITLE
Cannot retrieve real width and height of a new visual object created using default

### ISSUE THREAD

**Issue by rchevallier** [archimatetool/archi-scripting-plugin#71]
### Version
jarchi version 0.7.2
default visual element size in archi is 140x55 (cf attachment)
![image](https://user-images.githubusercontent.com/7887459/79586009-ddbe2380-80d0-11ea-94f5-6e829de093d3.png)

### Expected Behaviour
after creating a visual object with default height and width (-1), I expect to be able to retrieve the real values for width and height (the default ones) when getting the bound property

### Actual Behaviour
the value returned for are still -1

### Steps to Reproduce the Behaviour (with attached test files/script)
script:
```
console.clear()
console.show()
var model = selection.first().model
var comp = model.createElement("application-component", "New Component")
var cView = model.createArchimateView("Test view")
console.log("adding object to (10,10) default width and height")
var vo = cView.add(comp, 10, 10, -1, -1)
console.log("Visual object bounds: " + vo.bounds)
console.log("NB: width x height = " + vo.bounds.width + " x " +vo.bounds.height)
```

output is:
```
adding object to (10,10) default width and height
Visual object bounds: {x=10, width=-1, y=10, height=-1}
NB: width x height = -1 x -1
```

**Comment by Phillipus** [comment]
I'm not sure how or if this should be handled differently. Knowing that the value is -1 can be useful. To get the actual value would mean to query the user preferences, which of course will be different per Archi installation. So, the options are:

- keep it as is and return -1
- query user prefs and return actual value
- have an additional method or parameter when returning the bounds of an object

**Comment by Phillipus** [comment]
* add an API to get user preferences

**Comment by Phillipus** [comment]
Earlier versions of Archi stored the width and height as -1 if the size was the default size but this resulted in the model showing different displayed sizes on different Archi instances if the defaults were different. Now new objects created in Archi have the actual width and height values set and stored according to the user's preferences.

What should happen in jArchi is the same, so that when a value of -1 is given it should be replaced with the user's preferences value.

I'll fix this for the next version of jArchi.

**Comment by Phillipus** [comment]
Added to jArchi 0.8.0.
